[package]
name = "audiocap-lib"
version = "0.1.0"
edition = "2021"

[lib]
name = "audiocap_lib"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
which = "6.0"
ctrlc = "3.4"
libc = "0.2"

